### ISSUE TITLE
How to install with foreman?

### ISSUE THREAD

**Issue by e-it** [ab5w/puppet-csf#1]
Hello,

unfortunately I can not install this module on my puppet master using foreman. The class is not recognized.

How can I change that?

**Comment by ab5w** [comment]
Hey there,

What method are you using for the install of the module?

**Comment by e-it** [comment]
Hi,

I downloaded zip and unzipped it to module's folder.

**Comment by ab5w** [comment]
Ok so it looks like this?

~]# tree /etc/puppet/modules/csf/
/etc/puppet/modules/csf/
└── manifests
    ├── blackhole.pp
    ├── del_blackhole.pp
    ├── init.pp
    ├── lf.pp
    └── tcp.pp

1 directory, 5 files

Can you manually include it ok in your manifests?

**Comment by e-it** [comment]
Hello and thanks a lot for your reply,

the module is located in `/etc/puppet/environments/production/modules/sensson-csf` because I'm using it in `foreman`-environment (module-path: `/etc/puppet/environments/production/modules/`).

The tree looks like this:

```
sensson-csf/
├── manifests
│   ├── allow.pp
│   ├── config.pp
│   ├── deny.pp
│   ├── global.pp
│   ├── ignore.pp
│   ├── init.pp
│   ├── install.pp
│   ├── ipv4
│   │   ├── input.pp
│   │   └── output.pp
│   └── rule.pp
├── metadata.json
├── README.md
└── templates
    ├── csf.conf.rb
    ├── csf_header.rb
    ├── csf_rule.rb
    └── csf_vpn.rb

```

So you think I have to manually include it to another module which I can assign to a server using `foreman`?

**Comment by e-it** [comment]
Sorry, my mistake. The tree is from another module. Your tree is correct.

**Comment by ab5w** [comment]
You can't use two classes with the same declared name. You either need to rename one of the installed csf classes or delete one.
